import { Platform, Share } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export type ReceiptPdfInput = {
  receiptNumber: string;
  receiptDate: string;
  depositDate?: string;
  studentName: string;
  admissionNumber?: string;
  className?: string;
  amount: number;
  paymentMethod: string;
  notes?: string;
  schoolName: string;
  breakdowns?: Array<{ account: string; amount: number }>;
  generatedBy?: string;
  balanceAfter?: number | null;
};

function kes(n: number): string {
  return `KES ${(Number(n) || 0).toLocaleString('en-KE', { minimumFractionDigits: 2 })}`;
}

/** Official-style receipt HTML (mirrors Desk ReceiptPreview) for expo-print → PDF. */
export function buildReceiptHtml(r: ReceiptPdfInput): string {
  const rows = (r.breakdowns?.length
    ? r.breakdowns
    : [{ account: 'School fees payment', amount: r.amount }]
  )
    .map(
      (b) =>
        `<tr><td>${escapeHtml(b.account)}</td><td class="right">${escapeHtml(kes(b.amount))}</td></tr>`,
    )
    .join('');
  const balanceRow =
    typeof r.balanceAfter === 'number'
      ? `<p><strong>Balance after:</strong> ${escapeHtml(kes(r.balanceAfter))}</p>`
      : '';
  const notes = r.notes?.trim()
    ? `<p><strong>Notes:</strong> ${escapeHtml(r.notes.trim())}</p>`
    : '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(r.receiptNumber || 'Receipt')}</title>
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #111; margin: 28px; font-size: 13px; }
    h1 { font-size: 22px; margin: 0 0 4px; color: #15411D; }
    h2 { font-size: 18px; margin: 0; letter-spacing: 0.04em; }
    .muted { color: #555; font-size: 12px; }
    .header { border-bottom: 2px solid #15411D; padding-bottom: 12px; margin-bottom: 16px; }
    .title { text-align: center; border-bottom: 1px solid #ccc; padding-bottom: 12px; margin-bottom: 16px; }
    .grid { display: flex; gap: 24px; margin-bottom: 18px; }
    .grid > div { flex: 1; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0 18px; }
    th, td { border: 1px solid #ccc; padding: 8px; }
    th { background: #f4f4f4; text-align: left; }
    .right { text-align: right; }
    .total td { font-weight: bold; background: #f4f4f4; }
    .foot { margin-top: 28px; padding-top: 12px; border-top: 1px solid #ccc; font-size: 11px; color: #666; text-align: center; }
    .sig { margin-top: 36px; width: 160px; border-top: 1px solid #333; text-align: center; font-size: 12px; padding-top: 4px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(r.schoolName || 'School')}</h1>
    <p class="muted">Official fee receipt · Powered by Tukua</p>
  </div>
  <div class="title">
    <h2>OFFICIAL RECEIPT</h2>
    <p class="muted">Receipt No: ${escapeHtml(r.receiptNumber)}</p>
  </div>
  <div class="grid">
    <div>
      <p><strong>Receipt Date:</strong> ${escapeHtml(r.receiptDate || '—')}</p>
      <p><strong>Deposit Date:</strong> ${escapeHtml(r.depositDate || r.receiptDate || '—')}</p>
      <p><strong>Payment Method:</strong> ${escapeHtml(r.paymentMethod || '—')}</p>
    </div>
    <div>
      <p><strong>Student Name:</strong> ${escapeHtml(r.studentName || '—')}</p>
      <p><strong>ADM No:</strong> ${escapeHtml(r.admissionNumber || 'N/A')}</p>
      ${r.className ? `<p><strong>Class:</strong> ${escapeHtml(r.className)}</p>` : ''}
      ${balanceRow}
    </div>
  </div>
  <table>
    <thead>
      <tr><th>Vote head / account</th><th class="right">Amount</th></tr>
    </thead>
    <tbody>
      ${rows}
      <tr class="total"><td class="right">TOTAL</td><td class="right">${escapeHtml(kes(r.amount))}</td></tr>
    </tbody>
  </table>
  ${notes}
  <p><strong>Generated by:</strong> ${escapeHtml(r.generatedBy || 'Accounts')}</p>
  <div class="sig">Authorized Signature</div>
  <div class="foot">
    <p>This is an official receipt issued by ${escapeHtml(r.schoolName || 'the school')}.</p>
    <p>Powered by <strong>TukuPay</strong> · Banking Partner: <strong>Co-op Bank</strong></p>
  </div>
</body>
</html>`;
}

/** Map a parent-statement receipt row into PDF input. */
export function receiptRowToPdfInput(
  row: Record<string, unknown>,
  opts: {
    studentName?: string | null;
    schoolName?: string | null;
    admissionNumber?: string | null;
    className?: string | null;
  } = {},
): ReceiptPdfInput {
  const amount = Number(row.amount ?? row.total_amount ?? 0) || 0;
  const method = String(row.payment_method ?? row.method ?? '—').replace(/_/g, ' ');
  return {
    receiptNumber: String(row.receipt_number ?? row.id ?? '—'),
    receiptDate: String(row.receipt_date ?? row.created_at ?? '').slice(0, 10) || '—',
    depositDate: row.deposit_date
      ? String(row.deposit_date).slice(0, 10)
      : undefined,
    studentName:
      opts.studentName ||
      String(row.student_name ?? row.studentName ?? opts.studentName ?? '—'),
    admissionNumber:
      opts.admissionNumber ||
      (row.student_number != null ? String(row.student_number) : undefined) ||
      (row.admission_number != null ? String(row.admission_number) : undefined),
    className: opts.className || (row.class != null ? String(row.class) : undefined),
    amount,
    paymentMethod: method.toUpperCase(),
    notes: String(row.notes ?? row.narration ?? row.description ?? '').trim() || undefined,
    schoolName: opts.schoolName || 'School',
    generatedBy: String(row.generated_by ?? row.created_by_name ?? 'Accounts'),
    balanceAfter:
      typeof row.balance_after === 'number'
        ? row.balance_after
        : row.balance_after != null
          ? Number(row.balance_after)
          : null,
    breakdowns: Array.isArray(row.account_breakdowns)
      ? (row.account_breakdowns as Array<{ account?: string; amount?: number }>).map((b) => ({
          account: String(b.account ?? 'Payment'),
          amount: Number(b.amount ?? 0) || 0,
        }))
      : undefined,
  };
}

/**
 * Generate a real PDF via expo-print and share/save it.
 * Does not fall back to plain-text share when PDF succeeds.
 */
export async function shareReceiptPdfFromInput(input: ReceiptPdfInput): Promise<string> {
  const title = `Receipt ${input.receiptNumber}`;
  const { uri } = await Print.printToFileAsync({
    html: buildReceiptHtml(input),
    base64: false,
  });

  if (Platform.OS === 'web') {
    await Share.share({ title, url: uri, message: title });
    return uri;
  }

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: title,
      UTI: 'com.adobe.pdf',
    });
    return uri;
  }

  await Share.share({
    title,
    url: uri,
  });
  return uri;
}

/** @deprecated Prefer shareReceiptPdfFromInput with structured receipt fields. */
export async function shareReceiptPdf(body: string, title: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({
    html: `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${escapeHtml(title)}</title>
      <style>body{font-family:Georgia,serif;padding:24px;white-space:pre-wrap}</style></head>
      <body><h1>${escapeHtml(title)}</h1><pre>${escapeHtml(body)}</pre></body></html>`,
    base64: false,
  });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: title,
      UTI: 'com.adobe.pdf',
    });
    return;
  }
  await Share.share({ title, url: uri });
}
